# Generated by Django 2.2.3 on 2019-07-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
