# Generated by Django 2.2.3 on 2019-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resizer', '0002_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
            ],
        ),
    ]
